# Generated by Django 4.2.20 on 2025-04-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearTrack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('professeur', 'professeur'), ('Admin', 'Admin'), ('Utilisateur', 'Utilisateur')], default='Utilisateur', max_length=200),
        ),
    ]
