# Generated by Django 4.2.20 on 2025-03-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('epreuve_corrigee', 'Épreuve corrigée'), ('epreuve_non_corrigee', 'Épreuve non corrigée')], max_length=80)),
                ('matiere', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_hash', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
