# Generated by Django 4.2.20 on 2025-03-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_document_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
