# Generated by Django 4.2.20 on 2025-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='niveau',
            field=models.CharField(choices=[('bts_dut', 'Bts dut'), ('licence', 'Licence'), ('master_1', 'Master 1'), ('master_2', 'master 2'), ('doctorat', 'Doctoratt')], default='Bts dut', max_length=80),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('epreuve_corrigee', 'Épreuve corrigée'), ('epreuve_non_corrigee', 'Épreuve non corrigée'), ('cours', 'Cours')], max_length=80),
        ),
    ]
