# Generated by Django 4.2.20 on 2025-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_document_niveau_alter_document_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='niveau',
            field=models.CharField(choices=[('bts_dut', 'Bts dut'), ('licence', 'Licence'), ('master_1', 'Master 1'), ('master_2', 'master 2'), ('doctorat', 'Doctoratt')], default='Bts dut', max_length=80, null=True),
        ),
    ]
